openapi: 3.2.0
info:
  description: '# Overview

    ### Introduction

    Use the Sense API to synchronize your ATS data into the Sense Platform.'
  title: Sense Authentication API
  version: ''
servers:
- url: https://partner-api.us-stage.sensehq.co
security:
- sense_bearer_auth: []
tags:
- description: Authenticate using client credentials to obtain a Bearer access_token.
  name: Authentication
paths:
  /oauth2/token:
    post:
      description: Authenticate using client credentials to obtain a Bearer access_token.
      operationId: postTokenAuthorizer
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/sense_authentication_request'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sense_authentication_response'
          description: Authenticated successfully.
      security:
      - sense_authentication: []
      servers:
      - url: https://partner-auth.us-stage.sensehq.co
      summary: Authenticate
      tags:
      - Authentication
components:
  schemas:
    sense_authentication_response:
      properties:
        access_token:
          type: string
        expires_in:
          type: number
        token_type:
          type: string
    sense_authentication_request:
      properties:
        client_id:
          type: string
        client_secret:
          type: string
        grant_type:
          type: string
  securitySchemes:
    sense_authentication:
      flows:
        clientCredentials:
          scopes:
            N/A: The Sense API does not require a scope to be provided.
          tokenUrl: https://partner-auth.us-stage.sensehq.co/oauth2/token
      type: oauth2
    sense_bearer_auth:
      bearerFormat: JWT
      scheme: bearer
      type: http
